### ISSUE TITLE
Workflow property assignement in worklfow method doesn't work with task result

### ISSUE THREAD

**Issue by GauthierHacout** [infiniticio/infinitic#179] opened 2022-11-24 17:20 UTC
Hi Gilles!
I discovered an interesting bug (?) in a workflow. Assigning the result of a task to a property of a class, it seems not to work.
Here is an example of what I mean:
```
class WorkflowImpl: Workflow(), LoyaltyChildTasksWorkflow {
  private val eventTask: EventTask = newService(EventTask::class.java)
  private lateinit var enrichedEvent: EnrichedEventDTO

  override fun start(e: EnrichedEventDTO) {
    this.enrichedEvent = e
  }

  override fun processEvent(): WorkflowResult {

    // VERSION 0 : THIS DOESN'T WORK
    enrichedEvent.event.uniqueId = eventTask.getUniqueID(enrichedEvent, super.workflowId)    

    // VERSION 1 : THIS DOES WORK 
    val uniqueId: Long = eventTask.getUniqueID(enrichedEvent, super.workflowId)
    enrichedEvent.event.uniqueId = uniqueId

    inline { LOGGER.info { "My enriched event ID : ${enrichedEvent.event.uniqueId}" } }

    return WorkflowResult.SUCCESS 
  }
}
```

Knowing of course that eventTask.getUniqueID() returns a Long & that enrichedEvent is an object of a classic data class that never posed a problem otherwise.
I've simplified the workflow a lot to show only what I'm interested in in this case, but overall we create the workflow, then we call the start() method & then we call processEvent(). And there the version 0, assignement to enrichedEvent.event.uniqueId is not working.
So when the workflow keeps going, other tasks will see enrichedEvent.event.uniqueId as it was before the assignement (aka as given in the start() method), and not with the result of the task eventTask.getUniqueID().

The fix is pretty simple since version 1 works but I think it might be interesting to understand why ! If you need more information don't hesitate to ask me !

**Comment by geomagilles** [comment] 2022-12-17 10:21
this unfortunate behavior can be reproduced with:
```
class Foo(val id: UUID = UUID.randomUUID()) {
    var i: Int = 0
        get() {
            println("for $id - get i = $field")
            return field
        }
        set(value: Int) {
            println("for $id - set i = $value")
            field = value
        }
}
fun main() {
    var t = Foo()

    t.i = 1.also { t = Foo() }
    println(t.i) // => 0

    val i = 1.also { t = Foo() }
    t.i = i
    println(t.i) // => 1
}
```
executing `main` gives:
```
for 560e3784-9f47-4432-a86d-9230067be1e5 - set i = 1
for 1ab15268-bb97-4889-9152-0bc4003bfc4f - get i = 0
0
for cb2d0340-377c-4224-a1b9-35d528be8546 - set i = 1
for cb2d0340-377c-4224-a1b9-35d528be8546 - get i = 1
1
```
In your example, Infinitic automatically reset `enrichedEvent` property after the completion of the `getUniqueID` task - this is normal behavior to take into account any modification of the property during the task execution. But it creates an issue here because you update `enrichedEvent`  in the same statement. 

Ideally, we should try to update `enrichedEvent` instead of creating a new object

**Comment by geomagilles** [comment] 2023-06-11 21:21
Hi, I'm closing it as it won't be fixed. (Actually it may be fixed later by a much larger change)

**Closed by geomagilles** 2023-06-11 21:21 UTC
Labels: wontfix
